### ISSUE TITLE
Cache DNS requests

### ISSUE THREAD

**Issue by makew0rld** [opentimestamps/javascript-opentimestamps#103]
I'm using this library in a database that timestamps data entries. When inserting data asynchronously, this means many OTS requests happen at once. One of the problems with this is an explosion of DNS requests, which slows things down and also puts load on the DNS server. In my case I actually hit my Pi-Hole rate limit.

Here are some screenshots from my DNS server (Pi-hole) showing the issue:

![image](https://github.com/user-attachments/assets/baa64d39-2ee7-4715-808c-818ee7f7836b)
![image](https://github.com/user-attachments/assets/06730d00-3095-4145-be62-19386024d8c6)
![image](https://github.com/user-attachments/assets/d6f9d151-94f1-4b33-9c89-125504d89d10)

I will be rate-limiting my code to reduce load on the calendar servers too, but I just wanted to flag that if there's a way to do DNS caching that would be helpful.

Notably many of the requests were for `AAAA ots.btc.catallaxy.com`, which (1) doesn't exist and (2) isn't relevant because I am on an IPv4-only network.

**Comment by lvaccaro** [comment]
Hi @makew0rld , do you use the library on your local npm project or in a web page?

You could reduce the number of requests by passing to the `stamp()` function the list of calendars you want to use; with a list of calendars you could avoid to use `ots.btc.catallaxy.com` (if you don't need it) and avoid too make 3/4 requests with 3 proofs for each stamp.

A Native DNS caching for lookups discussion is available at https://github.com/nodejs/node/issues/5893 . 
Moreover the [dns.promises.Resolver](https://nodejs.org/api/dns.html#resolveroptions) could be replaced by using [DNS over HTTPS](https://en.wikipedia.org/wiki/DNS_over_HTTPS) ("DoH"), as: https://www.npmjs.com/package/tangerine , https://www.npmjs.com/package/dns-over-http-resolver

**Comment by makew0rld** [comment]
I'm using Node. I see now that not caching is a stdlib default and out of your control. Thanks for the links!

**Comment by petertodd** [comment]
FYI, something that could help you here is the [Foxglove Aggregator](https://github.com/opentimestamps/foxglove). It's a timestamp request aggregator that you can run locally that accepts multiple timestamp requests at once, builds a merkle tree of them, and then submits just a single request upstream. If you ran it locally, no matter how many timestamps were requested in a given time period, just one would go upstream.

Unfortunately, Foxglove doesn't yet submit to *multiple* upstream calendars at once. So if you want redundancy, you'll need to run multiple Foxglove instances at once, one for each upstream calendar. But that's a feature I can add to it in the future if people need it; at the moment the sole purpose of Foxglove is to provide a way to scale the calendars themselves.

**Comment by makew0rld** [comment]
Interesting, thanks!
