### ISSUE TITLE
issue with examples/index

### ISSUE THREAD

**Issue by MakorKa** [opentimestamps/javascript-opentimestamps#12]
Hi

When i try to use examples js, i get this error in console:

> $ node examples/test.js
STAMP
INFO
err=TypeError: Cannot read property '_HASHLIB_NAME' of undefined
(node:21181) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Invalid input
(node:21181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What this can be? 

Latest version, npm install updated all modules.

Thanks

**Comment by RCasatta** [comment]
Hi,

sorry but the example/test.js is an old file which isn't used anymore. I just removed the file https://github.com/opentimestamps/javascript-opentimestamps/commit/ce9a84fe8afffde4fe02195c26546c6b8b03b5cd

If you need to test the library please run `npm test` and for documentation and examples have a look at the README.md or inside the `test` folder
