### ISSUE TITLE
Timestamping a possibly large number of serialized JSON documents

### ISSUE THREAD

**Issue by domwoe** [opentimestamps/javascript-opentimestamps#15]
For my use case, I need to regularly timestamp a (possibly) large number of JSON documents, that need independent proofs. This means I need to be able to verify the timestamp of each JSON document individually, i.e. I can't just timestamp a list of the documents.

The obvious solution is to create a merkle tree of the documents and I'd like to have a merkle proof that is compatible to the OpenTimestamps format.

The stamp function in open-timestamps.js already allows a list of files as an argument but I'm not sure how they are handled. Does providing my documents as an array to this function already meet my requirements or do I need to build a merkle tree myself and stamp the root. And then store local merkle proofs in addition to the global timestamp from OpenTimestamps.

**Comment by lvaccaro** [comment]
Hi, 
The library method [stamp](https://github.com/opentimestamps/javascript-opentimestamps/blob/7429d35011350f4df29c53b45b76b87adff62ee8/src/open-timestamps.js#L102) already supports an array of data to stamp in DetachedTimestampFile format.
```js
 stamp(detaches, options) {
```
A DetachedTimestampFile contains the hash of your document to stamp and the pointer in the merkle tree: any DetachedTimestampFile is a tip of the merkle tree. You can get a DetachedTimestampFile object from a file or any hash hex string, like the following:
```js
detached = OpenTimestamps.DetachedTimestampFile.fromBytes(new OpenTimestamps.Ops.OpSHA256(), file);
detached = DetachedTimestampFile.fromHash(new Ops.OpSHA256(), hash);
```
Then, stamp function builds a local merkle tree of your input datas, stamp only the local merkle root and create all the proofs. The proof is self-contained in the DetachedTimestampFile object. Upgrade and Verify functions use ots proof parameters in DetachedTimestampFile format.

If you want to stamp multiple files to get multiple ots binary proofs, follow the example:
* input : files, an array file path
* output : ots, an array of ots proof
```js
  const detaches = [];
  files.forEach(file => {
    const detached = DetachedTimestampFile.fromBytes(new Ops.OpSHA256(), new Context.StreamDeserialization(file));
    detaches.push(detached);
  });
  OpenTimestamps.stamp(detaches).then(() => {
    ots = [];
    detaches.forEach((timestamp, i) => {
      ots.push( timestamp.serializeToBytes() );
    });
  }).catch(err => {
    console.error(err);
  });
```

Check the multi-file stamp test at [test file](https://github.com/opentimestamps/javascript-opentimestamps/blob/7429d35011350f4df29c53b45b76b87adff62ee8/test/open-timestamps.js#L177).

If you want to build your own merkle tree from an array of file, look at the
[makeMerkleTree](https://github.com/opentimestamps/javascript-opentimestamps/blob/7429d35011350f4df29c53b45b76b87adff62ee8/src/open-timestamps.js#L205) function.

**Comment by domwoe** [comment]
Thanks a lot. I'm incorporating your feedback right now!
