### ISSUE TITLE
npm WARN deprecated crypto@0.0.3

### ISSUE THREAD

**Issue by InnovativeInventor** [opentimestamps/javascript-opentimestamps#21]
Error message:

```
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```
It still seems to work though, so this isn't too urgent of an issue.

**Comment by RCasatta** [comment]
thanks for the heads up, will get rid of this dependency with the new version

**Comment by lvaccaro** [comment]
Thanks, removed `crypto` dep in 9936b7feca3137daa58335ae93a82c76074394c5 commit

**Comment by RCasatta** [comment]
We still need to publish the new package...

**Comment by RCasatta** [comment]
closing because has been deployed on npm
