### ISSUE TITLE
Wrong example in README.md for stamping a file from hash?

### ISSUE THREAD

**Issue by kas84** [opentimestamps/javascript-opentimestamps#24]
Hi, I am a newbie so sorry if I am asking a stupid question.

In this example from the readme, we are passing a Buffer to the fromHash function that is expecting an int Array.
https://github.com/opentimestamps/javascript-opentimestamps/blob/master/src/detached-timestamp-file.js#L155
```
const hash = Buffer.from('05c4f616a8e5310d19d938cfd769864d7f4ccdc2ca8b479b10af83564b097af9');
detached = DetachedTimestampFile.fromHash(new Ops.OpSHA256(), hash);
```
I took a look at the CLI, and when using -d you are converting the hex to byteArray like this:

```
function hexToBytes(hex) {
  const bytes = []
  for (let c = 0; c < hex.length; c += 2) {
    bytes.push(parseInt(hex.substr(c, 2), 16))
  }
  return bytes
}
```
Cheers!

**Comment by lvaccaro** [comment]
Hi @kas84, thanks for your feedback. From 3e4df86fd2cf1729b50fa2d2aefc82552c7556b9 commit, hash could be a buffer as described in README.md .
