### ISSUE TITLE
I am getting "Unknown operation tag:  00" when upgrading an OTS

### ISSUE THREAD

**Issue by santillaner** [opentimestamps/javascript-opentimestamps#27]
My code has been working fine, but since today, I am getting "Unknown operation tag:  00" when trying to upgrade OTSs. 

After that console.error, I get "TypeError: Cannot read property 'call' of undefined".

**Comment by lvaccaro** [comment]
@santillaner could you upload your ots file? could you share your code?

**Comment by santillaner** [comment]
Hi there. Cannot post complete source code. The failing OTS's are: 
SHA256: e83b9c6a84e83e363a752b65d18d1d1057eeab15dc471a1d5245b3fbaf7712d5
OTS: 004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108e83b9c6a84e83e363a752b65d18d1d1057eeab15dc471a1d5245b3fbaf7712d5f0109879dd7318c4429ba2a8c81f2dd34b8b08

And also:
SHA256: 89bd26b075be2ec271f25e8555c1038d3731b01331a00553d14262f2738af665
OTS: 004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010889bd26b075be2ec271f25e8555c1038d3731b01331a00553d14262f2738af665f010fe8f062ea016da7da202ce8eda1da78208

**Comment by lvaccaro** [comment]
Hi @santillaner, your OTS is not valid because there are no Attestations, so the deserialization procedure fails. The following merkle tree ends with sha256 no attestations: 
`e83b9c6a84e83e363a752b65d18d1d1057eeab15dc471a1d5245b3fbaf7712d5` -> append `(f0)` `9879dd7318c4429ba2a8c81f2dd34b8b` -> sha256 `(08)`

**Comment by santillaner** [comment]
Hi @lvaccaro ! Seems like maybe a communications glitch, it happened twice the same day and it has not happened again. I'm closing this issue temporarily and if it happens again I'll reopen. Is that ok for you Luca?

cheers!
