### ISSUE TITLE
Upgrade function explanation

### ISSUE THREAD

**Issue by jwyuen** [opentimestamps/javascript-opentimestamps#28]
Sorry if this seems like a dumb question, but I don't quite understand what the upgrade function is supposed to do?  I've tried looking for some explanation of it somewhere but haven't been able to find one that explains it more in depth (even after looking at the code).

A comment in the code says: "Attempt to upgrade an incomplete timestamp to make it verifiable."  Based on what I understand of how opentimestamps works, you can't verify a timestamp until it has been confirmed on the Bitcoin blockchain, or you can verify an incomplete one by downloading it from a calendar server?

**Comment by RCasatta** [comment]
Verifying an incomplete receipt means asking the calendar server for the upgrade and checking the data against the blockchain.
So you can verify incomplete receipt but you are relying on the calendar server data, when you have an upgraded receipt you are no longer dependant on the calendar server.

**Comment by jwyuen** [comment]
So if you attempt to upgrade a timestamp before it has been recorded on the blockchain, the upgrade operation will fail?  Also if my line of thinking here is correct, when verifying a timestamp, verification only returns true IFIF it has been recorded on the blockchain?

**Comment by RCasatta** [comment]
Yes and yes,
Also, the calendar server will answer the upgrade operation only if the timestamping TX has 6 confirmations.
This is to handle reorgs

**Comment by jwyuen** [comment]
Thanks for the answers - much appreciated!

**Comment by jwyuen** [comment]
@petertodd oh and thanks for building opentimestamps - it's an awesome piece of technology!

**Comment by jwyuen** [comment]
Are timestamps automatically upgraded after some period of time or does an upgrade call need to be explicitly made?

**Comment by petertodd** [comment]
Timestamp *files* are not automatically upgraded. For example, if you run:

> $ ots stamp foo 
> Submitting to remote calendar https://a.pool.opentimestamps.org
> Submitting to remote calendar https://b.pool.opentimestamps.org
> Submitting to remote calendar https://a.pool.eternitywall.com
> Submitting to remote calendar https://ots.btc.catallaxy.com

The `foo.ots` file itself won't be modified in any way in the future; `ots` doesn't, for instance, leave a process running to upgrade it later behind your back (I actually considered doing this once and decided it was a very bad idea!).

But they *are* automatically upgraded in the sense that the calendars will automatically complete the timestamp and make that completed timestamp proof available indefinitely. So unless there's a total failure of the OTS community as a whole and everyone loses that calendar data you will be able to upgrade the timestamp later. Similarly, if you run `ots verify foo.ots` in the future, what verify is actually doing behind the scenes is exactly the same as `ots upgrade foo.ots`, except that verify doesn't write the upgraded proof back to the `foo.ots` file.

**Comment by escapedcat** [comment]
@jwyuen you think it's worth adding new infos generated by your issue into the docs? would you be up for it? really good questions!

**Comment by jwyuen** [comment]
@escapedcat yes for sure!  whenever I get some time I can make a pull request.

**Comment by jwyuen** [comment]
Another question - are timestamp operations idempotent?  Meaning if they aren't then I would need to store the generated .ots timestamp files even if my original data hasn't changed right?

**Comment by jwyuen** [comment]
Also it looks like timestamps are not always the same number of bytes - is there a maximum limit to the size of a timestamp?

**Comment by lvaccaro** [comment]
Hi, there is't a fixed size or a maximum dimension of a merkle tree. Depending on ots calendar work, you could retrieve a longer or shorter proof path. 
A year ago, @petertodd made a huge merkle tree, read the post [How OpenTimestamps 'Carbon Dated' (almost) The Entire Internet With One Bitcoin Transaction](https://petertodd.org/2017/carbon-dating-the-internet-archive-with-opentimestamps).
