### ISSUE TITLE
CORS violation doesn't trigger error path when verifying timestamp

### ISSUE THREAD

**Issue by jwyuen** [opentimestamps/javascript-opentimestamps#29]
Using the example code for verifying a timestamp in the browser, I get a CORS violation from trezor.io.  Interestingly this doesn't seem to trigger the error path and so it's difficult to recover from.  Perhaps an issue with whatever request client library is being used?

**Comment by lvaccaro** [comment]
Hi @jwyuen, lite client verification uses by default [6 public Insight Urls](https://github.com/opentimestamps/javascript-opentimestamps/blob/9992ab136b974410e43cd7237f6f57522358bb95/src/insight.js#L122) and return the block hash (if more than one insight replies, it checks block hash together ). 

Trezor's insight doesn't support CORS, so it fails inside the browser, but it could be used successfully server-side. Moreover insights are often not available ( https://search.bitaccess.co go to 504 ) and others are really slow. For this reason, in js-lib you can set the list of insight urls to use with option `insight.urls` ( see the javadoc of [verify](https://github.com/opentimestamps/javascript-opentimestamps/blob/7b81a36c977214f9659617c64976a70a1bac577d/src/open-timestamps.js#L244) ).
Anyway the best strategy is connect to a bitcoin peer node to perform the block verification.

**Comment by jwyuen** [comment]
Hello!

Yes I see what you mean now......I thought the requests had finished but they just took a long time to run.  On a related note, it looks like the timeout option doesn't seem to work properly or I'm using it incorrectly?

`
const verifyOptions = {
      timeout: 2,
      insight: {
        urls: [
          'https://www.localbitcoinschain.com/api',
          // 'https://search.bitaccess.co/insight-api',
          // 'https://insight.bitpay.com/api',
          'https://blockexplorer.com/api',
        `],`
      },
    };
```

**Comment by lvaccaro** [comment]
Hi, the `verifyOptions` are related to [verify function](https://github.com/opentimestamps/javascript-opentimestamps/blob/7b81a36c977214f9659617c64976a70a1bac577d/src/open-timestamps.js#L244). Insight options are grouped together by `insight` field: `urls` and `timeout` should be define inside `insight`.
In #32 MR, added `Pass options` test for MultiInsight.
