### ISSUE TITLE
Serializing and Deserializing do not work as expected

### ISSUE THREAD

**Issue by jwyuen** [opentimestamps/javascript-opentimestamps#31]
Hello!

I'm attempting to serialize a DetachedTimestamp object after stamping data so that I can send it to a database for storage.  When retrieving this stored data, deserializing the data either returns error or doesn't return the data as I would expect.  In simplified terms:

```
OpenTimestamps.stamp(detachedTimestamp, options).then(() => {

          const serializedTimestamp = detachedTimestamp.serializeToBytes();

          // This will return an error
          const detachedOts = OpenTimestamps.DetachedTimestampFile.deserialize(serializedTimestamp);

          // This will return a valid DetachedTimestampFile but it will fail verification below
          const detachedOts = OpenTimestamps.DetachedTimestampFile.fromBytes(new OpenTimestamps.Ops.OpSHA256(), serializedTimestamp);

          console.log(detachedTimestamp);
          console.log(detachedOts);
          infoResult = OpenTimestamps.info(detachedTimestamp);
          console.log(infoResult);
          infoResult = OpenTimestamps.info(detachedOts);
          console.log(infoResult);


          const whitelist = new UrlWhitelist([
            'https://*.calendar.opentimestamps.org', 
            // 'https://*.calendar.eternitywall.com', 
            'https://*.calendar.catallaxy.com', 
          ]);

          const options = {
            timeout: 2,
            insight: {
              chain: 'bitcoin',
              urls: [
                'https://www.localbitcoinschain.com/api',
                'https://blockexplorer.com/api',
                // 'https://search.bitaccess.co/insight-api',
                // 'https://insight.bitpay.com/api',
              ],
            },
            whitelist,
          };

          OpenTimestamps.verify(detachedOts, detachedTimestamp, options).then((verifyResult) => {
            console.log(verifyResult);
          })
          .catch((err) => {
            console.error(err);
          });

}); 

```

Is my usage or assumption of what the serializeToBytes(), deserialize(), and fromBytes() functions incorrect, or have I encountered a bug here?

**Comment by jwyuen** [comment]
Thanks for the clarification!

The error I'm seeing when I use `deserialize` is:

```
ops.js:77 Unknown operation tag:  00
```

Btw I included the verify function mostly for debugging since my original problem was that I was trying to figure out why my original timestamp and my timestamp created from deserialized byte array were different.

Anyways, it looks like if I can figure out why deserialize isn't working that would pretty much solve my problem....  Maybe the issue is that I'm running the code in a browser?  More specifically I'm running it on a react + webpack setup on Chromium Version 68.0.3440.75 (Developer Build) built on Debian 9.5, running on Debian 9.5 (64-bit)

**Comment by lvaccaro** [comment]
What version of the library are you using? Can you attach your parameters?
`OpenTimestamps.stamp(detachedTimestamp, options).then(() => {`

Compare your parameters with this working example on JS
https://gist.github.com/lvaccaro/f9e0aa000227e3fcf84c6cdeb5b39fb1#file-ots_test_in_browser-js
 or test directly on [JSFiddle console](https://jsfiddle.net/0wg23yn6/17/).

**Comment by jwyuen** [comment]
Ya running your code works.  It also looks like my code works once I remove options from stamp().  The options I was using that was causing the error are:

```
        const stampOptions = {
          calendars: [
            'https://*.calendar.opentimestamps.org', // Run by Peter Todd
            // 'https://*.calendar.eternitywall.com', // Run by Riccardo Casatta of Eternity Wall
            'https://*.calendar.catallaxy.com', // Run by Vincent Cloutier of Catallaxy
          ],
        };
```

**Comment by lvaccaro** [comment]
You are using `calendars` instead of `whitelist`option:
* `calendar`: url of calendars to override default calendars (not grouped).
* `whitelist`: list of remote calendar to accept as valid (grouped as you defined).
