### ISSUE TITLE
Insight response error: RequestError: Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by dari08s** [opentimestamps/javascript-opentimestamps#33]
Hi,
I'm using the library i 2 servers. In the first one there is the previous version of the library, in the second on the most updated. The second one has some problems related to the verification, when I run the verify cmd or I upload the generated ots on the opentimestamps.org page it results pending even if I execute an upgrade. Here's the error:
Could not connect to local Bitcoin node
Could not connect to local Bitcoin node
Could not connect to local Bitcoin node
Insight response error: StatusCodeError: 429 - undefined
Insight response error: RequestError: Error: ESOCKETTIMEDOUT
Lite-client verification, assuming block 0000000000000000000c1c00408ff682a07e5ad82851416f495717bdf01c8002 is valid
Insight response error: RequestError: Error: ESOCKETTIMEDOUT
Lite-client verification, assuming block 000000000000000000139f4685ebfb3d3d638718038ffc13d1227f6e9aceabe3 is valid
Insight response error: RequestError: Error: ESOCKETTIMEDOUT
Lite-client verification, assuming block 000000000000000000139f4685ebfb3d3d638718038ffc13d1227f6e9aceabe3 is valid
Insight response error: StatusCodeError: 429 - undefined
Insight response error: RequestError: Error: ESOCKETTIMEDOUT
Insight response error: RequestError: Error: ESOCKETTIMEDOUT
Insight response error: RequestError: Error: ESOCKETTIMEDOUT
Success! Bitcoin block 538014 attests existence as of 2018-08-23 CEST

Why am I also no more able to see the Time Stamp Hours details?

Thanks in advance

**Comment by lvaccaro** [comment]
> it results pending even if I execute an upgrade.
 1. It could requires a few hours for the timestamp to get confirmed by the Bitcoin blockchain; calendars are not doing one transaction per timestamp. 
You can use `info` command to get information on a timestamp,  including the actual commitment operations and attestations in it (pending and completed attestations).

2. By default, js library stamps on multiple calendars and provides for each calendar a different pending attestion. 
   * Upgrade command: upgrades only attestations that are ready on calendar (confirmed by the Bitcoin blockchain)
   * Verify command: verify all completed attestations and reveal only the attestation at minimum height.

3. The last js release displays Bitcoin timestamps with appropriate precision (so without hours), as @petertodd described in [his commit](https://github.com/opentimestamps/opentimestamps-client/commit/44a1951c22ac9b9487ad1c6af5af2e672c22ce19).

**Comment by dari08s** [comment]
Thanks for your answer

Dario
