### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by jotae1e** [opentimestamps/javascript-opentimestamps#37]
Hi all

This is not a bug, it's a "requirement" about the documentation of the functions of OpenTimeStamps.

¿What is the concrete use of the method UPGRADE?

Sorry, but I searched, but I can't find documentation of the purpose of this method.

Thanks a lot.

**Comment by escapedcat** [comment]
Did you see the paragraph in the README here: https://github.com/opentimestamps/javascript-opentimestamps#upgrade

Help of `ots-cli.js` says this:
```
upgrade|u [options] [FILE_OTS]  Upgrade remote calendar timestamps to be locally verifiable
```
Does this help to clearify things?  
If I understand it correctly it makes it  independently verifiable from the calendar service.

**Comment by jotae1e** [comment]
Yes, I have read the info a lot of times.  

Correctme if I am wrong.  I understand this:

If  I use ots file without upgrade, It has the references to the calendars, and I can use this file to know the date with the function info.

When I use the function upgrade, it delete the references to the calendars and put all the info of the calendars in this file.

Then, how I can test this file, because the info method not works.  I understand that all the info is in this file, but how can I test it?

Thanks a lot.

**Comment by escapedcat** [comment]
Not sure I can follow you.  
I did an `upgrade` for `merkle1.txt.ots` from the [example folder here](https://github.com/opentimestamps/javascript-opentimestamps/tree/master/examples).  

Like this:
```
ots-cli.js upgrade merkle1.txt.ots
Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
Success! Timestamp complete
The file .bak was saved!
```

After this I can call `info` and get the result, like this:
```
ots-cli.js info merkle1.txt.ots
File sha256 hash: d32fee9a827f5a0d580f80beb7edce662dd99fcd6591e4ef8a6244403df0b7c9
Timestamp:
append 0201a36ac0c73692d1cedcabff0609eb
sha256
append 9f42984ccdb96addb79884e714cc6b6b059c68f2ac3a2e07c5198c22d904de14
...
```

**Comment by jotae1e** [comment]
Well.  It work well from command line.  I know.  

I am working in javascript with this example:

`
    const ruta_fichero_ots = require('path').resolve(sails.config.appPath) + '/sellostiempoweb/' + registro.id_usuario + '/' + registro.uid_fichero + '.pdf.ots';
    const fichero_ots_buffer = await fs.readFile(ruta_fichero_ots);
    let detachedOts = OpenTimestamps.DetachedTimestampFile.deserialize(fichero_ots_buffer);
    // const infoResult = OpenTimestamps.info(detachedOts);


    OpenTimestamps.upgrade(detachedOts).then((changed) => {
      if (changed) {
        console.log('Timestamp upgraded');
        const upgradedFileOts = detachedOts.serializeToBytes();
        const infoResult = OpenTimestamps.info(upgradedFileOts);
        console.log.info(infoResult)

        return exits.success(infoResult);
      } else {
        console.log('Timestamp not upgraded');
      }
    }).catch(err => {
      console.log(err);
    });
`

But throws an error in line:

const infoResult = OpenTimestamps.info(upgradedFileOts);

The error is:

`
Got 1 attestation(s) from https://finney.calendar.eternitywall.com
Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org
Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org
Got 1 attestation(s) from https://btc.calendar.catallaxy.com
Timestamp upgraded
TypeError: Cannot read property '_HASHLIB_NAME' of undefined
    at Object.info (/certifirm/SailsBE_dev/node_modules/javascript-opentimestamps/src/open-timestamps.js:39:40)
    at OpenTimestamps.upgrade.then (/certifirm/SailsBE_dev/api/controllers/test1.js:47:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by jotae1e** [comment]
Sorry, I must use the buffer directly.  This works well.  My mistake.
`
async function test() {

    let ruta_fichero_ots = 'test.pdf.ots';
    let fichero_ots_buffer = await fs.readFile(ruta_fichero_ots);
    let detachedOts = OpenTimestamps.DetachedTimestampFile.deserialize(fichero_ots_buffer);
    
    let cambiado = await OpenTimestamps.upgrade(detachedOts)

    if (cambiado) {
        let infoResult = OpenTimestamps.info(detachedOts);
        console.log(infoResult);
        console.log('Timestamp upgraded');
    } else {
        console.log('Timestamp not upgraded');
    }


}
`

**Comment by escapedcat** [comment]
I think you can use `verify` to check.  

Like this:
```
ots-cli.js verify merkle1.txt.ots
Assuming target filename is 'merkle1.txt'
Could not connect to local Bitcoin node
Could not connect to local Bitcoin node
Insight response error: StatusCodeError: 502 - "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n\n\n<title>www.localbitcoinschain.com | 502: Bad gateway</title>
...
<a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div><!-- /.error-footer -->\n\n\n    </div><!-- /#cf-error-details -->\n</div><!-- /#cf-wrapper -->\n</body>\n</html>\n"
Insight response error: StatusCodeError: 400 - "Can't read block from disk. Code:-32603"
Success! Bitcoin block 429808 attests existence as of 2016-09-14 CEST
```

I am not completely sure but it looks like it tries to verify it via a locally installed Bitcoin node (if available) and through (*some*) public nodes.  
`www.localbitcoinschain.com` seems to be down that's why you get the error message in between. But in the end it looks like it got verified by at least one node (without going through the calendar service).  

I'm also still learning.

**Comment by jotae1e** [comment]
Yes, I know that verify, verifies the .ots against calendar services, and I think that if .ots was upgraded, we can verify it without calendar servicies, but using ots-cli. 

But the question that I asked it's if we can verify without this ots-cli (not dependant of this repo).

**Comment by jotae1e** [comment]
I am reading a lot of documentation of blockchain and opentimestamps (not in this site) and now I understand all the process.  I think that the documentation can be better, but my English is not enough  good to write it.

Thanks a lot.

**Comment by escapedcat** [comment]
WOuld you mind linking the posts/sites you read? Maybe their content could be used to extend the current docs here.
