### ISSUE TITLE
Verify ots

### ISSUE THREAD

**Issue by bionicco** [opentimestamps/javascript-opentimestamps#4]
I've a problem with verify.
After making a stamp I save  the result in a DB.
If I call info with the result I obtain some info,
 but verifying the result (even after days) will end with a undefined response!

It seems that that the verifyTimestamp function exit because both the attestation are Notary.PendingAttestation and no action is taken,

**Comment by RCasatta** [comment]
The standard procedure is to call the commands in this order stamp -> upgrade -> verify
In the last version [0.1.19](https://github.com/opentimestamps/javascript-opentimestamps/releases/tag/0.1.19) we implemented an implicit call to upgrade when calling verify from the command line. If you try to verify an incomplete receipt
```
node ots-cli.js verify examples/incomplete.txt.ots
```
you will get
```
Assuming target filename is 'examples/incomplete.txt'
Timestamp upgraded
Success! Bitcoin attests data existed as of Wed Sep 07 2016 07:56:43 GMT+0200 (CEST)
```

Note that this is the standard behaviour from the command line, while the verify method inside the library does not upgrade the receipt by default

**Comment by bionicco** [comment]
Thanks, after trying to upgrade I understood how it works! Maybe could be usefull this beavior also in the library
