### ISSUE TITLE
claim opentimestamps on npm

### ISSUE THREAD

**Issue by thisconnect** [opentimestamps/javascript-opentimestamps#53]
As stuff on npm usually is JavaScript it would be more natural if the npm package would just be named `opentimestamps`, i.e. `$ npm install -g opentimestamps`. The repo name on github is fine as it is.

Would somebody from @opentimestamps / @eternitywall be interested to publish if as opentimestamps?

**Comment by RCasatta** [comment]
make sense to me

@lvaccaro what do you think?

**Comment by thisconnect** [comment]
just let me know which npm user should be the new owner

**Comment by RCasatta** [comment]
the npm user is eternitywall

**Comment by thisconnect** [comment]
yes I see, eternitywall is publisher of https://www.npmjs.com/package/javascript-opentimestamps 
transfering to https://www.npmjs.com/~eternitywall

**Comment by thisconnect** [comment]
```bash
$ npm owner ls opentimestamps
eerne 
$ npm owner add eternitywall opentimestamps
+ eternitywall (opentimestamps)
$ npm owner ls opentimestamps
eerne
```
🤔 not sure if that worked I kinda expected to see eternitywall listed now,
 https://docs.npmjs.com/cli/owner

can you try to publish opentimestamps ? 
let me know if that worked, then I'll try to remove myself

**Comment by thisconnect** [comment]
ah opentimestamps now appears under https://www.npmjs.com/~eternitywall and
```
$ npm owner ls opentimestamps
eerne
eternitywall
```
as expected. It just needed a bit of time to update.

**Comment by thisconnect** [comment]
```
$ npm owner rm eerne opentimestamps
- eerne (opentimestamps)
```

ok I tried to `npm version 0.0.1` and `npm publish` and got
```
npm ERR! code E403
npm ERR! 403 Forbidden - PUT https://registry.npmjs.org/opentimestamps - You do not have permission to publish "opentimestamps". Are you logged in as the correct user?
```

**Comment by thisconnect** [comment]
please test :)

**Comment by lvaccaro** [comment]
Thanks and concept ack

I think npm doesn't support redirect, so we can mark the previous package as deprecated with redirect message https://docs.npmjs.com/cli/deprecate and add a disclaimer in README.md as @RCasatta made in https://github.com/opentimestamps/javascript-opentimestamps/pull/65

**Comment by RCasatta** [comment]
https://github.com/opentimestamps/javascript-opentimestamps/pull/65 merged, finally we migrated to the new name (old one deprecated)
thanks @thisconnect
