### ISSUE TITLE
Problem in upgradeStamp() ?

### ISSUE THREAD

**Issue by LaurentMT** [opentimestamps/javascript-opentimestamps#6]
Hi there,

I've started to play with the library and I've just noticed something strange in function upgradeStamp().

It seems the function always resolves (even when an error is catched).

As a consequence, the array promises[] managed by upgradeTimestamp(() is fed with undefined values (line 417) which means that test done on line 434 (results.length === 0) is always evaluated to true and that upgrade() returns true even if the timestamp hasn't been upgraded.

**Comment by lvaccaro** [comment]
Thanks LaurentMT, changed the behaviour of upgradeTimestamp() merged [here](https://github.com/opentimestamps/javascript-opentimestamps/commit/cb27f72e02c6fa0a6a25bc7884b0ede208d46f4d).
The procedure always resolves but now with a different param.
```
results.forEach(result => {
             if (result !== undefined) {
              changed = true;
              result.subStamp.merge(result.upgradedStamp);
            }
          });
          resolve(changed);
```
Can you check again?

**Comment by RCasatta** [comment]
any update @LaurentMT ?

**Comment by LaurentMT** [comment]
Hi there,
Sorry for my long silence. I just checked the code and that seems good. I close the issue.
Thanks lvaccaro for the fix !
