### ISSUE TITLE
Replace Array.size() by Array.length

### ISSUE THREAD

**Issue by LaurentMT** [opentimestamps/javascript-opentimestamps#7]
opentimestamps.js has several occurrences of a call to Array.size() method (e.g.: lined 128 & 146).

This method isn't supported in js and the calls raise an exception. To be replaced by Array.length

**Comment by RCasatta** [comment]
Could you please create a pull request for this? I'll be glad to merge it

**Comment by LaurentMT** [comment]
Sure.

**Comment by RCasatta** [comment]
PR merged, closing issue
