### ISSUE TITLE
stamp file return URL is not defined

### ISSUE THREAD

**Issue by pzaccount** [opentimestamps/javascript-opentimestamps#74]
I downloaded last version of opentimestamps and when I try to stamp the file with ots-cli.js I see the message `URL is not defined`. Below my command line test :  `node ots-cli.js s test-certification.txt`  console result `URL is not defined`. Where is URL  configured?

Thanks a lot.

**Comment by lvaccaro** [comment]
Hi @pzaccount, which version of node are you using?

There should be a URL global variable on node 10 and in modern browser, but it should be better make it explicit as the following (where it is used):
`var URL = require('url').URL;`

**Comment by pzaccount** [comment]
The node version used is 6.14.3.  Thanks for the clarification I understood the issue.
