### ISSUE TITLE
Unresponsive Insight servers

### ISSUE THREAD

**Issue by LaurentMT** [opentimestamps/javascript-opentimestamps#9]
Hi there,

Execution of Verify() function can be very long when an Insight server is unavailable (it's currently the case with www.localbitcoinschain.com which returns a timeout error).

I just noticed that the list of Insight servers used by the library is currently hardcoded and can't be overridden via an option.

Any interest for a pull request adding an options parameter to verify() function ? Basically, it would be something similar to the management of options in stamp() function. If options.insightUrls property is set, MultiInsight instance would use this list. Otherwise, it would default to the hardcoded list.

Additionally/alternatively, we could add a timeout option or a default timeout passed to the request-promise in order to override the default duration, which is a bit long (I suspect something around 15-20s).

**Comment by RCasatta** [comment]
We currently mantain a list of 6 publicly available insights so I don't think using others through options is very interesting also considering insight is a fallback option in absence of a local full node.
The timeout option is indeed interesting, we should have a 10 seconds default timeout which will be the maximum wait time in case some explorer takes more than 10 seconds to answer.
Even better we should mantain a queue of results and resolve the promise when the quickest two answer (with the same value).
The equality check from two different sources (which is already what the algo is doing) is against crazy answer from blockexplorers.
In the long term we want to switch to another validation against block which doesn't involve blockexplorers.

**Comment by petertodd** [comment]
FWIW Note how some users may choose to run their own insight server, e.g. within a firewalled network.

**Comment by petertodd** [comment]
FWIW Note how some users may choose to run their own insight server, e.g. within a firewalled network.

**Comment by RCasatta** [comment]
Insight run next to a bitcoin full node, I would ask the node in that case...

**Comment by petertodd** [comment]
True, although for some setups asking the insight node will be easier. :)

Also, helps run old versions of the software in the future if all the insight servers die.

**Comment by RCasatta** [comment]
Cool, any PRs for adding an option for insight urls is welcome!

**Comment by LaurentMT** [comment]
Ok. I'm going to work on that.
